In [ ]:
# Import and run the data generator
from data import Data

# Initialize data generator (cleanup happens automatically during __init__)
# data_gen = Data(seed=42, simbench_code='1-LV-rural2--1-no_sw')
data_gen = Data(seed=42, simbench_code='1-LV-rural3--2-no_sw')


# Generate data (config file is automatically loaded from initialization)
print("Starting data generation...\n")

filtered_dfs, time_range = data_gen.generate_consistent_copies()
print("\n✅ Data generation complete!")
print(f"Generated {len(filtered_dfs)} datasets")

🗑️ Cleaning up existing generated files...
✓ No existing files to delete

Found config file: data_config.json
Starting data generation...

Using SimBench code from instance: '1-LV-rural2--0-no_sw'

================================================================================
GENERATING CONSISTENT DATA SEQUENCE
================================================================================
Loading Load + RES + Storage from SimBench '1-LV-rural2--0-no_sw'...
Raw Load columns (25): 25
Raw Renewables columns (5): 5
Raw Storage columns (1): 1

Converting normalized profiles to absolute MW...
  Load units: 99 individual units converted to MW
  RES units: 8 individual generators converted to MW
  Storage units: 0 individual units converted to MW
✓ Profiles converted to absolute MW values
   load sample time: '01.01.2016 00:00'
   load time parsed with format: %d.%m.%Y %H:%M
   load: 99 columns (absolute MW)
   renewables sample time: '01.01.2016 00:00'
   renewables time parsed with format: %d.%m.%Y %H:%M
   renewables: 8 columns (absolute MW)
   storage DataFrame is empty, skipping time parsing

SimBench '1-LV-rural2--0-no_sw' loaded and converted to absolute MW:
   Loads:   35136 rows | 99 columns
   RES:     35136 rows | 8 columns
   Storage: 0 rows | 0 columns

================================================================================
LOADING PRICE DATA
================================================================================
Loading Day-Ahead price data...
Price file loaded: 35136 rows
   Available columns: ['Time from [CET/CEST]', 'Price EXAA 10:15 Auction [EUR/MWh]']
   Using date column: 'Time from [CET/CEST]' | price column: 'Price EXAA 10:15 Auction [EUR/MWh]'
   Sample time: '1/1/2016 0:00'
   Time parsed with format: mixed (auto-detect)
Day-Ahead Price loaded: 35132 rows
   📈 Range: -102.6 - 150.0 €/MWh
Generating Intraday prices from Day-Ahead prices...
Intraday Price generated: 35132 rows
   📈 Range: -109.8 - 163.5 €/MWh
   Average ID/DA ratio: 0.9999
   Randomization range: 0.90 - 1.10
Loading Imbalance price data...
Imbalance price file loaded: 35136 rows
   Available columns: ['Time from [CET/CEST]', 'Price final [EUR/MWh]']
   Using date column: 'Time from [CET/CEST]' | price column: 'Price final [EUR/MWh]'
Imbalance Price loaded: 35136 rows
   📈 Range: -4677.0 - 3017.8 €/MWh
Loading Retail Price...
   Retail Price: €201.00/MWh
Loading Feed-in Price...
   Feed-in Price: €82.40/MWh

Resampling to 15-minute intervals...
Generating Day-Ahead forecasts...
Generating Intraday forecasts...

Combining all prices...
Combined prices: 35144 rows
   DA_price range: -102.63 - 150.00 €/MWh
   ID_price range: -109.75 - 163.54 €/MWh
   Imbalance range: -4677.00 - 3017.78 €/MWh
   Retail (fixed): 201.00 €/MWh
   Feed-in (fixed): 82.40 €/MWh
Generating storage forecasts...

Filtering to specified time range...
Filtered to 35136 15-minute intervals: 2016-01-01 00:00:00 to 2016-12-31 23:45:00 (NAIVE)

Saving CSV files...
   💾 Saved: load_actual.csv (35136 rows)
   💾 Saved: load_forecast_da.csv (35136 rows)
   💾 Saved: load_forecast_id.csv (35136 rows)
   💾 Saved: res_actual.csv (35136 rows)
   💾 Saved: res_forecast_da.csv (35136 rows)
   💾 Saved: res_forecast_id.csv (35136 rows)
   💾 Saved: prices.csv (35136 rows)
   💾 Saved: storage_actual.csv (35136 rows)
   💾 Saved: storage_forecast_da.csv (35136 rows)
   💾 Saved: storage_forecast_id.csv (35136 rows)

================================================================================
🎉 COMPLETE DATA SEQUENCE GENERATED!
================================================================================
   📊 SimBench: '1-LV-rural2--0-no_sw'
   💰 DA Price: 'original/Day Ahead Preise_M15_2016.csv'
   💰 ID Price: Generated from DA (range: 0.90-1.10)
   💰 Imbalance: 'original/imbalance_prices.csv'
   💰 Retail: Fixed price from 'original/retail_price.csv'
   💰 Feed-in: Fixed price from 'original/feedin_price.csv'
   🌱 Seed: 42
   ⏰ Intervals: 35136 × 15-min
   📁 Output: './'
   📈 Datasets: 10 CSV files (Load + RES + Storage (Actual + DA + ID) + Prices)
   ⏰ ALL TIMES NAIVE (NO TIMEZONE)
================================================================================


✅ Data generation complete!
Generated 10 datasets

In [2]:
# Display Load Actual data
print("📊 LOAD ACTUAL DATA (MW)")
print("="*80)
print(f"Shape: {filtered_dfs['load_actual'].shape}")
print(f"Columns: {len(filtered_dfs['load_actual'].columns)}")
print(f"\nFirst 5 rows:")
filtered_dfs['load_actual'].head()

📊 LOAD ACTUAL DATA (MW)
================================================================================
Shape: (35136, 100)
Columns: 100

First 5 rows:

,datetime,LV2.101 Load 9 [H0-C],LV2.101 Load 85 [G3-A],LV2.101 Load 82 [G5-A],LV2.101 Load 52 [H0-C],LV2.101 Load 12 [H0-C],LV2.101 Load 49 [H0-B],LV2.101 Load 10 [H0-A],LV2.101 Load 42 [H0-B],LV2.101 Load 84 [G1-C],...,LV2.101 Load 4 [H0-C],LV2.101 Load 43 [H0-L],LV2.101 Load 50 [H0-B],LV2.101 Load 94 [G4-A],LV2.101 Load 65 [H0-A],LV2.101 Load 70 [H0-B],LV2.101 Load 57 [H0-L],LV2.101 Load 18 [H0-A],LV2.101 Load 55 [H0-G],LV2.101 Load 76 [H0-L]
0,2016-01-01 00:00:00,0.000237,0.002809,0.000802,0.000237,0.000237,0.000066,0.000277,0.000066,0.000625,...,0.000474,0.000107,0.000132,0.002598,0.000277,0.000132,0.000107,0.000277,0.000168,0.000054
1,2016-01-01 00:15:00,0.000067,0.002797,0.000744,0.000067,0.000067,0.000190,0.000066,0.000190,0.000306,...,0.000134,0.000040,0.000381,0.001763,0.000066,0.000381,0.000040,0.000066,0.000319,0.000020
2,2016-01-01 00:30:00,0.000064,0.003211,0.000758,0.000064,0.000064,0.000168,0.000206,0.000168,0.000279,...,0.000128,0.000043,0.000336,0.001703,0.000206,0.000336,0.000043,0.000206,0.000326,0.000021
3,2016-01-01 00:45:00,0.000065,0.003104,0.000787,0.000065,0.000065,0.000113,0.000128,0.000113,0.000292,...,0.000131,0.000034,0.000227,0.001814,0.000128,0.000227,0.000034,0.000128,0.000362,0.000017
4,2016-01-01 01:00:00,0.000076,0.003104,0.000845,0.000076,0.000076,0.000134,0.000108,0.000134,0.000292,...,0.000152,0.000055,0.000269,0.001805,0.000108,0.000269,0.000055,0.000108,0.000487,0.000028

In [3]:
# Print load columns list (excluding datetime, sorted by unit number)
import re

def extract_unit_id(col_name):
    """Extract unit number for sorting"""
    match = re.search(r'Load\s+(\d+)', col_name)
    return int(match.group(1)) if match else 0

sorted([col for col in filtered_dfs['load_actual'].columns if col != 'datetime'], key=extract_unit_id)

['LV2.101 Load 1 [H0-L]',
 'LV2.101 Load 2 [H0-B]',
 'LV2.101 Load 3 [H0-L]',
 'LV2.101 Load 4 [H0-C]',
 'LV2.101 Load 5 [H0-B]',
 'LV2.101 Load 6 [H0-G]',
 'LV2.101 Load 7 [H0-G]',
 'LV2.101 Load 8 [H0-A]',
 'LV2.101 Load 9 [H0-C]',
 'LV2.101 Load 10 [H0-A]',
 'LV2.101 Load 11 [H0-A]',
 'LV2.101 Load 12 [H0-C]',
 'LV2.101 Load 13 [H0-B]',
 'LV2.101 Load 14 [H0-G]',
 'LV2.101 Load 15 [H0-G]',
 'LV2.101 Load 16 [H0-L]',
 'LV2.101 Load 17 [H0-A]',
 'LV2.101 Load 18 [H0-A]',
 'LV2.101 Load 19 [H0-B]',
 'LV2.101 Load 20 [H0-L]',
 'LV2.101 Load 21 [H0-B]',
 'LV2.101 Load 22 [H0-L]',
 'LV2.101 Load 23 [H0-L]',
 'LV2.101 Load 24 [H0-C]',
 'LV2.101 Load 25 [H0-A]',
 'LV2.101 Load 26 [H0-G]',
 'LV2.101 Load 27 [H0-L]',
 'LV2.101 Load 28 [H0-C]',
 'LV2.101 Load 29 [H0-G]',
 'LV2.101 Load 30 [H0-B]',
 'LV2.101 Load 31 [H0-C]',
 'LV2.101 Load 32 [H0-L]',
 'LV2.101 Load 33 [H0-A]',
 'LV2.101 Load 34 [G6-A]',
 'LV2.101 Load 35 [H0-G]',
 'LV2.101 Load 36 [H0-B]',
 'LV2.101 Load 37 [H0-B]',
 'LV2.101 Load 38 [H0-L]',
 'LV2.101 Load 39 [H0-L]',
 'LV2.101 Load 40 [H0-A]',
 'LV2.101 Load 41 [H0-G]',
 'LV2.101 Load 42 [H0-B]',
 'LV2.101 Load 43 [H0-L]',
 'LV2.101 Load 44 [H0-C]',
 'LV2.101 Load 45 [H0-A]',
 'LV2.101 Load 46 [H0-A]',
 'LV2.101 Load 47 [H0-L]',
 'LV2.101 Load 48 [H0-A]',
 'LV2.101 Load 49 [H0-B]',
 'LV2.101 Load 50 [H0-B]',
 'LV2.101 Load 51 [H0-G]',
 'LV2.101 Load 52 [H0-C]',
 'LV2.101 Load 53 [H0-C]',
 'LV2.101 Load 54 [H0-A]',
 'LV2.101 Load 55 [H0-G]',
 'LV2.101 Load 56 [H0-A]',
 'LV2.101 Load 57 [H0-L]',
 'LV2.101 Load 58 [H0-L]',
 'LV2.101 Load 59 [H0-C]',
 'LV2.101 Load 60 [H0-L]',
 'LV2.101 Load 61 [H0-L]',
 'LV2.101 Load 62 [H0-B]',
 'LV2.101 Load 63 [H0-A]',
 'LV2.101 Load 64 [H0-B]',
 'LV2.101 Load 65 [H0-A]',
 'LV2.101 Load 66 [H0-A]',
 'LV2.101 Load 67 [H0-A]',
 'LV2.101 Load 68 [H0-B]',
 'LV2.101 Load 69 [H0-C]',
 'LV2.101 Load 70 [H0-B]',
 'LV2.101 Load 71 [H0-G]',
 'LV2.101 Load 72 [H0-L]',
 'LV2.101 Load 73 [H0-A]',
 'LV2.101 Load 74 [H0-L]',
 'LV2.101 Load 75 [H0-A]',
 'LV2.101 Load 76 [H0-L]',
 'LV2.101 Load 77 [H0-L]',
 'LV2.101 Load 78 [H0-C]',
 'LV2.101 Load 79 [H0-L]',
 'LV2.101 Load 80 [H0-C]',
 'LV2.101 Load 81 [H0-B]',
 'LV2.101 Load 82 [G5-A]',
 'LV2.101 Load 83 [H0-B]',
 'LV2.101 Load 84 [G1-C]',
 'LV2.101 Load 85 [G3-A]',
 'LV2.101 Load 86 [H0-C]',
 'LV2.101 Load 87 [H0-A]',
 'LV2.101 Load 88 [H0-B]',
 'LV2.101 Load 89 [H0-G]',
 'LV2.101 Load 90 [H0-L]',
 'LV2.101 Load 91 [G1-B]',
 'LV2.101 Load 92 [H0-B]',
 'LV2.101 Load 93 [H0-C]',
 'LV2.101 Load 94 [G4-A]',
 'LV2.101 Load 95 [G2-A]',
 'LV2.101 Load 96 [H0-A]',
 'LV2.101 Load 97 [H0-L]',
 'LV2.101 Load 98 [H0-G]',
 'LV2.101 Load 99 [H0-G]']

In [4]:
# Print RES columns list (excluding datetime, sorted by unit number)
import re

def extract_unit_id(col_name):
    """Extract unit number for sorting"""
    match = re.search(r'SGen\s+(\d+)', col_name)
    return int(match.group(1)) if match else 0

sorted([col for col in filtered_dfs['res_actual'].columns if col != 'datetime'], key=extract_unit_id)

['LV2.101 SGen 1 [PV7]',
 'LV2.101 SGen 2 [PV3]',
 'LV2.101 SGen 3 [PV7]',
 'LV2.101 SGen 4 [PV4]',
 'LV2.101 SGen 5 [PV4]',
 'LV2.101 SGen 6 [PV3]',
 'LV2.101 SGen 7 [PV3]',
 'LV2.101 SGen 8 [PV1]']

In [5]:
# Print storage columns list (excluding datetime, sorted by unit number)
import re

def extract_unit_id(col_name):
    """Extract unit number for sorting"""
    match = re.search(r'Storage\s+(\d+)', col_name)
    return int(match.group(1)) if match else 0

sorted([col for col in filtered_dfs['storage_actual'].columns if col != 'datetime'], key=extract_unit_id)

[]

In [6]:
# Display all units grouped by Bus, Type, and ordered by unit number
import re
import pandas as pd


def parse_column_name(col_name):
    """Parse column name to extract bus, type, and unit number"""
    match = re.match(r'LV\d+\.(\d+)\s+(Load|SGen|Storage)\s+(\d+)', col_name)
    if match:
        bus_num = int(match.group(1))
        unit_type = match.group(2)
        unit_num = int(match.group(3))
        return bus_num, unit_type, unit_num, col_name
    return None, None, None, None


def extract_units_from_dataframe(df, unit_type_name):
    """Extract units from a dataframe and return as DataFrame ordered by unit number"""
    units_data = []
    for col in df.columns:
        if col != 'datetime':
            bus, utype, unum, fullname = parse_column_name(col)
            if bus is not None:
                units_data.append({
                    'bus': bus,
                    'unit_type': unit_type_name,
                    'unit_number': unum,
                    'full_name': fullname
                })
    
    units_df = pd.DataFrame(units_data)
    if not units_df.empty:
        units_df = units_df.sort_values('unit_number').reset_index(drop=True)
    return units_df


# Step 1: Create dataframes for loads, res, and storage (ordered by unit number)
loads_df = extract_units_from_dataframe(filtered_dfs['load_actual'], 'Load')
res_df = extract_units_from_dataframe(filtered_dfs['res_actual'], 'SGen')
storages_df = extract_units_from_dataframe(filtered_dfs['storage_actual'], 'Storage')

# Step 2: Combine all units and group by bus and unit type, ordered by unit number
all_units_df = pd.concat([loads_df, res_df, storages_df], ignore_index=True)
all_units_df = all_units_df.sort_values(['bus', 'unit_type', 'unit_number']).reset_index(drop=True)

# Step 3: Display with proper cascading structure
print("📊 ALL UNITS GROUPED BY BUS AND TYPE")
print("="*80)
print(f"Total units: {len(all_units_df)}\n")

current_bus = None
current_type = None

for idx, row in all_units_df.iterrows():
    # New bus
    if row['bus'] != current_bus:
        current_bus = row['bus']
        current_type = None
        print(f"\n🔹 BUS {current_bus}")
    
    # New unit type within the same bus
    if row['unit_type'] != current_type:
        current_type = row['unit_type']
        print(f"   ├── {current_type}")
    
    # Display unit (check if it's the last unit in this type for proper tree formatting)
    next_idx = idx + 1
    is_last_in_type = (next_idx >= len(all_units_df) or 
                       all_units_df.iloc[next_idx]['bus'] != current_bus or 
                       all_units_df.iloc[next_idx]['unit_type'] != current_type)
    
    if is_last_in_type:
        print(f"   │   └── Unit {row['unit_number']}: {row['full_name']}")
    else:
        print(f"   │   ├── Unit {row['unit_number']}: {row['full_name']}")

print("\n" + "="*80)

📊 ALL UNITS GROUPED BY BUS AND TYPE
================================================================================
Total units: 107


🔹 BUS 101
   ├── Load
   │   ├── Unit 1: LV2.101 Load 1 [H0-L]
   │   ├── Unit 2: LV2.101 Load 2 [H0-B]
   │   ├── Unit 3: LV2.101 Load 3 [H0-L]
   │   ├── Unit 4: LV2.101 Load 4 [H0-C]
   │   ├── Unit 5: LV2.101 Load 5 [H0-B]
   │   ├── Unit 6: LV2.101 Load 6 [H0-G]
   │   ├── Unit 7: LV2.101 Load 7 [H0-G]
   │   ├── Unit 8: LV2.101 Load 8 [H0-A]
   │   ├── Unit 9: LV2.101 Load 9 [H0-C]
   │   ├── Unit 10: LV2.101 Load 10 [H0-A]
   │   ├── Unit 11: LV2.101 Load 11 [H0-A]
   │   ├── Unit 12: LV2.101 Load 12 [H0-C]
   │   ├── Unit 13: LV2.101 Load 13 [H0-B]
   │   ├── Unit 14: LV2.101 Load 14 [H0-G]
   │   ├── Unit 15: LV2.101 Load 15 [H0-G]
   │   ├── Unit 16: LV2.101 Load 16 [H0-L]
   │   ├── Unit 17: LV2.101 Load 17 [H0-A]
   │   ├── Unit 18: LV2.101 Load 18 [H0-A]
   │   ├── Unit 19: LV2.101 Load 19 [H0-B]
   │   ├── Unit 20: LV2.101 Load 20 [H0-L]
   │   ├── Unit 21: LV2.101 Load 21 [H0-B]
   │   ├── Unit 22: LV2.101 Load 22 [H0-L]
   │   ├── Unit 23: LV2.101 Load 23 [H0-L]
   │   ├── Unit 24: LV2.101 Load 24 [H0-C]
   │   ├── Unit 25: LV2.101 Load 25 [H0-A]
   │   ├── Unit 26: LV2.101 Load 26 [H0-G]
   │   ├── Unit 27: LV2.101 Load 27 [H0-L]
   │   ├── Unit 28: LV2.101 Load 28 [H0-C]
   │   ├── Unit 29: LV2.101 Load 29 [H0-G]
   │   ├── Unit 30: LV2.101 Load 30 [H0-B]
   │   ├── Unit 31: LV2.101 Load 31 [H0-C]
   │   ├── Unit 32: LV2.101 Load 32 [H0-L]
   │   ├── Unit 33: LV2.101 Load 33 [H0-A]
   │   ├── Unit 34: LV2.101 Load 34 [G6-A]
   │   ├── Unit 35: LV2.101 Load 35 [H0-G]
   │   ├── Unit 36: LV2.101 Load 36 [H0-B]
   │   ├── Unit 37: LV2.101 Load 37 [H0-B]
   │   ├── Unit 38: LV2.101 Load 38 [H0-L]
   │   ├── Unit 39: LV2.101 Load 39 [H0-L]
   │   ├── Unit 40: LV2.101 Load 40 [H0-A]
   │   ├── Unit 41: LV2.101 Load 41 [H0-G]
   │   ├── Unit 42: LV2.101 Load 42 [H0-B]
   │   ├── Unit 43: LV2.101 Load 43 [H0-L]
   │   ├── Unit 44: LV2.101 Load 44 [H0-C]
   │   ├── Unit 45: LV2.101 Load 45 [H0-A]
   │   ├── Unit 46: LV2.101 Load 46 [H0-A]
   │   ├── Unit 47: LV2.101 Load 47 [H0-L]
   │   ├── Unit 48: LV2.101 Load 48 [H0-A]
   │   ├── Unit 49: LV2.101 Load 49 [H0-B]
   │   ├── Unit 50: LV2.101 Load 50 [H0-B]
   │   ├── Unit 51: LV2.101 Load 51 [H0-G]
   │   ├── Unit 52: LV2.101 Load 52 [H0-C]
   │   ├── Unit 53: LV2.101 Load 53 [H0-C]
   │   ├── Unit 54: LV2.101 Load 54 [H0-A]
   │   ├── Unit 55: LV2.101 Load 55 [H0-G]
   │   ├── Unit 56: LV2.101 Load 56 [H0-A]
   │   ├── Unit 57: LV2.101 Load 57 [H0-L]
   │   ├── Unit 58: LV2.101 Load 58 [H0-L]
   │   ├── Unit 59: LV2.101 Load 59 [H0-C]
   │   ├── Unit 60: LV2.101 Load 60 [H0-L]
   │   ├── Unit 61: LV2.101 Load 61 [H0-L]
   │   ├── Unit 62: LV2.101 Load 62 [H0-B]
   │   ├── Unit 63: LV2.101 Load 63 [H0-A]
   │   ├── Unit 64: LV2.101 Load 64 [H0-B]
   │   ├── Unit 65: LV2.101 Load 65 [H0-A]
   │   ├── Unit 66: LV2.101 Load 66 [H0-A]
   │   ├── Unit 67: LV2.101 Load 67 [H0-A]
   │   ├── Unit 68: LV2.101 Load 68 [H0-B]
   │   ├── Unit 69: LV2.101 Load 69 [H0-C]
   │   ├── Unit 70: LV2.101 Load 70 [H0-B]
   │   ├── Unit 71: LV2.101 Load 71 [H0-G]
   │   ├── Unit 72: LV2.101 Load 72 [H0-L]
   │   ├── Unit 73: LV2.101 Load 73 [H0-A]
   │   ├── Unit 74: LV2.101 Load 74 [H0-L]
   │   ├── Unit 75: LV2.101 Load 75 [H0-A]
   │   ├── Unit 76: LV2.101 Load 76 [H0-L]
   │   ├── Unit 77: LV2.101 Load 77 [H0-L]
   │   ├── Unit 78: LV2.101 Load 78 [H0-C]
   │   ├── Unit 79: LV2.101 Load 79 [H0-L]
   │   ├── Unit 80: LV2.101 Load 80 [H0-C]
   │   ├── Unit 81: LV2.101 Load 81 [H0-B]
   │   ├── Unit 82: LV2.101 Load 82 [G5-A]
   │   ├── Unit 83: LV2.101 Load 83 [H0-B]
   │   ├── Unit 84: LV2.101 Load 84 [G1-C]
   │   ├── Unit 85: LV2.101 Load 85 [G3-A]
   │   ├── Unit 86: LV2.101 Load 86 [H0-C]
   │   ├── Unit 87: LV2.101 Load 87 [H0-A]
   │   ├── Unit 88: LV2.101 Load 88 [H0-B]
   │   ├── Unit 89: LV2.101 Load 89 [H0-G]
   │   ├── Unit 90: LV2.101 Load 90 [H0-L]
   │   ├── Unit 91: LV2.101 Load 91 [G1-B]
   │   ├── Unit 92: LV2.101 Load 92 [H0-B]
   │   ├── Unit 93: LV2.101 Load 93 [H0-C]
   │   ├── Unit 94: LV2.101 Load 94 [G4-A]
   │   ├── Unit 95: LV2.101 Load 95 [G2-A]
   │   ├── Unit 96: LV2.101 Load 96 [H0-A]
   │   ├── Unit 97: LV2.101 Load 97 [H0-L]
   │   ├── Unit 98: LV2.101 Load 98 [H0-G]
   │   └── Unit 99: LV2.101 Load 99 [H0-G]
   ├── SGen
   │   ├── Unit 1: LV2.101 SGen 1 [PV7]
   │   ├── Unit 2: LV2.101 SGen 2 [PV3]
   │   ├── Unit 3: LV2.101 SGen 3 [PV7]
   │   ├── Unit 4: LV2.101 SGen 4 [PV4]
   │   ├── Unit 5: LV2.101 SGen 5 [PV4]
   │   ├── Unit 6: LV2.101 SGen 6 [PV3]
   │   ├── Unit 7: LV2.101 SGen 7 [PV3]
   │   └── Unit 8: LV2.101 SGen 8 [PV1]

================================================================================

In [7]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


all_units_df

     bus unit_type  unit_number               full_name
0    101      Load            1   LV2.101 Load 1 [H0-L]
1    101      Load            2   LV2.101 Load 2 [H0-B]
2    101      Load            3   LV2.101 Load 3 [H0-L]
3    101      Load            4   LV2.101 Load 4 [H0-C]
4    101      Load            5   LV2.101 Load 5 [H0-B]
5    101      Load            6   LV2.101 Load 6 [H0-G]
6    101      Load            7   LV2.101 Load 7 [H0-G]
7    101      Load            8   LV2.101 Load 8 [H0-A]
8    101      Load            9   LV2.101 Load 9 [H0-C]
9    101      Load           10  LV2.101 Load 10 [H0-A]
10   101      Load           11  LV2.101 Load 11 [H0-A]
11   101      Load           12  LV2.101 Load 12 [H0-C]
12   101      Load           13  LV2.101 Load 13 [H0-B]
13   101      Load           14  LV2.101 Load 14 [H0-G]
14   101      Load           15  LV2.101 Load 15 [H0-G]
15   101      Load           16  LV2.101 Load 16 [H0-L]
16   101      Load           17  LV2.101 Load 17 [H0-A]
17   101      Load           18  LV2.101 Load 18 [H0-A]
18   101      Load           19  LV2.101 Load 19 [H0-B]
19   101      Load           20  LV2.101 Load 20 [H0-L]
20   101      Load           21  LV2.101 Load 21 [H0-B]
21   101      Load           22  LV2.101 Load 22 [H0-L]
22   101      Load           23  LV2.101 Load 23 [H0-L]
23   101      Load           24  LV2.101 Load 24 [H0-C]
24   101      Load           25  LV2.101 Load 25 [H0-A]
25   101      Load           26  LV2.101 Load 26 [H0-G]
26   101      Load           27  LV2.101 Load 27 [H0-L]
27   101      Load           28  LV2.101 Load 28 [H0-C]
28   101      Load           29  LV2.101 Load 29 [H0-G]
29   101      Load           30  LV2.101 Load 30 [H0-B]
30   101      Load           31  LV2.101 Load 31 [H0-C]
31   101      Load           32  LV2.101 Load 32 [H0-L]
32   101      Load           33  LV2.101 Load 33 [H0-A]
33   101      Load           34  LV2.101 Load 34 [G6-A]
34   101      Load           35  LV2.101 Load 35 [H0-G]
35   101      Load           36  LV2.101 Load 36 [H0-B]
36   101      Load           37  LV2.101 Load 37 [H0-B]
37   101      Load           38  LV2.101 Load 38 [H0-L]
38   101      Load           39  LV2.101 Load 39 [H0-L]
39   101      Load           40  LV2.101 Load 40 [H0-A]
40   101      Load           41  LV2.101 Load 41 [H0-G]
41   101      Load           42  LV2.101 Load 42 [H0-B]
42   101      Load           43  LV2.101 Load 43 [H0-L]
43   101      Load           44  LV2.101 Load 44 [H0-C]
44   101      Load           45  LV2.101 Load 45 [H0-A]
45   101      Load           46  LV2.101 Load 46 [H0-A]
46   101      Load           47  LV2.101 Load 47 [H0-L]
47   101      Load           48  LV2.101 Load 48 [H0-A]
48   101      Load           49  LV2.101 Load 49 [H0-B]
49   101      Load           50  LV2.101 Load 50 [H0-B]
50   101      Load           51  LV2.101 Load 51 [H0-G]
51   101      Load           52  LV2.101 Load 52 [H0-C]
52   101      Load           53  LV2.101 Load 53 [H0-C]
53   101      Load           54  LV2.101 Load 54 [H0-A]
54   101      Load           55  LV2.101 Load 55 [H0-G]
55   101      Load           56  LV2.101 Load 56 [H0-A]
56   101      Load           57  LV2.101 Load 57 [H0-L]
57   101      Load           58  LV2.101 Load 58 [H0-L]
58   101      Load           59  LV2.101 Load 59 [H0-C]
59   101      Load           60  LV2.101 Load 60 [H0-L]
60   101      Load           61  LV2.101 Load 61 [H0-L]
61   101      Load           62  LV2.101 Load 62 [H0-B]
62   101      Load           63  LV2.101 Load 63 [H0-A]
63   101      Load           64  LV2.101 Load 64 [H0-B]
64   101      Load           65  LV2.101 Load 65 [H0-A]
65   101      Load           66  LV2.101 Load 66 [H0-A]
66   101      Load           67  LV2.101 Load 67 [H0-A]
67   101      Load           68  LV2.101 Load 68 [H0-B]
68   101      Load           69  LV2.101 Load 69 [H0-C]
69   101      Load           70  LV2.101 Load 70 [H0-B]
70   101      Load           71  LV2.101 Load 71 [H0-G]
71   101      Load           72  LV2.101 Load 72 [H0-L]
72   101      Load           73  LV2.101 Load 73 [H0-A]
73   101      Load           74  LV2.101 Load 74 [H0-L]
74   101      Load           75  LV2.101 Load 75 [H0-A]
75   101      Load           76  LV2.101 Load 76 [H0-L]
76   101      Load           77  LV2.101 Load 77 [H0-L]
77   101      Load           78  LV2.101 Load 78 [H0-C]
78   101      Load           79  LV2.101 Load 79 [H0-L]
79   101      Load           80  LV2.101 Load 80 [H0-C]
80   101      Load           81  LV2.101 Load 81 [H0-B]
81   101      Load           82  LV2.101 Load 82 [G5-A]
82   101      Load           83  LV2.101 Load 83 [H0-B]
83   101      Load           84  LV2.101 Load 84 [G1-C]
84   101      Load           85  LV2.101 Load 85 [G3-A]
85   101      Load           86  LV2.101 Load 86 [H0-C]
86   101      Load           87  LV2.101 Load 87 [H0-A]
87   101      Load           88  LV2.101 Load 88 [H0-B]
88   101      Load           89  LV2.101 Load 89 [H0-G]
89   101      Load           90  LV2.101 Load 90 [H0-L]
90   101      Load           91  LV2.101 Load 91 [G1-B]
91   101      Load           92  LV2.101 Load 92 [H0-B]
92   101      Load           93  LV2.101 Load 93 [H0-C]
93   101      Load           94  LV2.101 Load 94 [G4-A]
94   101      Load           95  LV2.101 Load 95 [G2-A]
95   101      Load           96  LV2.101 Load 96 [H0-A]
96   101      Load           97  LV2.101 Load 97 [H0-L]
97   101      Load           98  LV2.101 Load 98 [H0-G]
98   101      Load           99  LV2.101 Load 99 [H0-G]
99   101      SGen            1    LV2.101 SGen 1 [PV7]
100  101      SGen            2    LV2.101 SGen 2 [PV3]
101  101      SGen            3    LV2.101 SGen 3 [PV7]
102  101      SGen            4    LV2.101 SGen 4 [PV4]
103  101      SGen            5    LV2.101 SGen 5 [PV4]
104  101      SGen            6    LV2.101 SGen 6 [PV3]
105  101      SGen            7    LV2.101 SGen 7 [PV3]
106  101      SGen            8    LV2.101 SGen 8 [PV1]

In [ ]:
# Draw SimBench network topology
import simbench as sb
import pandapower.plotting as plot
import matplotlib.pyplot as plt

# Load the SimBench network
net = sb.get_simbench_net('1-LV-urban6--2-no_sw')

# Create network visualization
print("🔌 SIMBENCH NETWORK TOPOLOGY")
print("="*80)
print(f"Network: 1-LV-urban6--2-no_sw")
print(f"Buses: {len(net.bus)}")
print(f"Lines: {len(net.line)}")
print(f"Loads: {len(net.load)}")
print(f"Generators (RES): {len(net.sgen)}")
print(f"Storage: {len(net.storage)}")
print(f"Transformers: {len(net.trafo)}")
print("\n")

# Plot the network
plt.figure(figsize=(16, 12))
plot.simple_plot(net, 
                 plot_loads=True, 
                 plot_sgens=True,
                 load_size=2.0,
                 sgen_size=2.0,
                 bus_size=1.5,
                 line_width=1.0,
                 respect_switches=True,
                 show_plot=False)

plt.title('SimBench Network: 1-LV-urban6--2-no_sw', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

print("="*80)